import { type EnvironmentProviders, inject, provideAppInitializer } from '@angular/core';
import { MatIconRegistry } from '@angular/material/icon';
import { DomSanitizer } from '@angular/platform-browser';
import {
  mdiAccountChildOutline,
  mdiAccountCircleOutline,
  mdiAccountGroupOutline,
  mdiAccountMultipleOutline,
  mdiAccountOutline,
  mdiAlertCircleOutline,
  mdiAlertOutline,
  mdiArrowDown,
  mdiArrowLeft,
  mdiArrowRight,
  mdiArrowUp,
  mdiCalendarCheckOutline,
  mdiCalendarMonthOutline,
  mdiChartBar,
  mdiChartBoxOutline,
  mdiCheck,
  mdiCheckAll,
  mdiCheckCircle,
  mdiCheckboxMarkedCircleOutline,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiCircleOutline,
  mdiClipboardCheckOutline,
  mdiClose,
  mdiCloudOffOutline,
  mdiCursorDefaultClickOutline,
  mdiCursorDefaultOutline,
  mdiDeleteOutline,
  mdiDotsVertical,
  mdiDownload,
  mdiEmailOutline,
  mdiEyeOffOutline,
  mdiEyeOutline,
  mdiFileSearchOutline,
  mdiFilterVariant,
  mdiFlaskOutline,
  mdiGenderFemale,
  mdiGenderMale,
  mdiGestureTap,
  mdiHandWaveOutline,
  mdiHomeCityOutline,
  mdiHomeOutline,
  mdiHumanMaleHeight,
  mdiInformationOutline,
  mdiLanDisconnect,
  mdiLockOutline,
  mdiLogin,
  mdiLogout,
  mdiMagnify,
  mdiMagnifyPlusOutline,
  mdiMapMarkerOutline,
  mdiMenu,
  mdiMicrosoftExcel,
  mdiMinus,
  mdiNoteTextOutline,
  mdiPencilOutline,
  mdiPlayCircleOutline,
  mdiPlus,
  mdiPuzzleOutline,
  mdiRefresh,
  mdiRestore,
  mdiSchoolOutline,
  mdiShieldAccountOutline,
  mdiTimerSandEmpty,
  mdiTranslate,
  mdiVideoOutline,
  mdiViewDashboardOutline,
  mdiWeightKilogram,
  mdiWifiOff,
} from '@mdi/js';

/**
 * The app's icons, by name: `<mat-icon svgIcon="children" />`. Only the icons listed here
 * are bundled (inline SVG paths from Material Design Icons, Apache 2.0).
 */
export const APP_ICONS: Readonly<Record<string, string>> = {
  account: mdiAccountCircleOutline,
  'account-outline': mdiAccountOutline,
  add: mdiPlus,
  admin: mdiShieldAccountOutline,
  'arrow-down': mdiArrowDown,
  'arrow-left': mdiArrowLeft,
  'arrow-right': mdiArrowRight,
  'arrow-up': mdiArrowUp,
  assessment: mdiClipboardCheckOutline,
  boy: mdiGenderMale,
  calendar: mdiCalendarMonthOutline,
  'calendar-check': mdiCalendarCheckOutline,
  center: mdiHomeCityOutline,
  chart: mdiChartBar,
  'chart-box': mdiChartBoxOutline,
  check: mdiCheck,
  'check-all': mdiCheckAll,
  'check-circle': mdiCheckCircle,
  'check-circle-outline': mdiCheckboxMarkedCircleOutline,
  'chevron-down': mdiChevronDown,
  'chevron-left': mdiChevronLeft,
  'chevron-right': mdiChevronRight,
  'chevron-up': mdiChevronUp,
  children: mdiAccountChildOutline,
  circle: mdiCircleOutline,
  click: mdiCursorDefaultClickOutline,
  close: mdiClose,
  dashboard: mdiViewDashboardOutline,
  delete: mdiDeleteOutline,
  demo: mdiFlaskOutline,
  domains: mdiPuzzleOutline,
  download: mdiDownload,
  edit: mdiPencilOutline,
  email: mdiEmailOutline,
  error: mdiAlertCircleOutline,
  excel: mdiMicrosoftExcel,
  eye: mdiEyeOutline,
  'eye-off': mdiEyeOffOutline,
  filter: mdiFilterVariant,
  girl: mdiGenderFemale,
  group: mdiAccountGroupOutline,
  height: mdiHumanMaleHeight,
  home: mdiHomeOutline,
  info: mdiInformationOutline,
  language: mdiTranslate,
  location: mdiMapMarkerOutline,
  lock: mdiLockOutline,
  login: mdiLogin,
  logout: mdiLogout,
  menu: mdiMenu,
  minus: mdiMinus,
  more: mdiDotsVertical,
  'not-found': mdiFileSearchOutline,
  notes: mdiNoteTextOutline,
  offline: mdiWifiOff,
  pending: mdiTimerSandEmpty,
  play: mdiPlayCircleOutline,
  pointer: mdiCursorDefaultOutline,
  refresh: mdiRefresh,
  reset: mdiRestore,
  school: mdiSchoolOutline,
  search: mdiMagnify,
  'server-off': mdiCloudOffOutline,
  'simulate-offline': mdiLanDisconnect,
  tap: mdiGestureTap,
  users: mdiAccountMultipleOutline,
  video: mdiVideoOutline,
  warning: mdiAlertOutline,
  wave: mdiHandWaveOutline,
  weight: mdiWeightKilogram,
  'zoom-in': mdiMagnifyPlusOutline,
};

function svg(path: string): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="${path}"/></svg>`;
}

export function provideAppIcons(): EnvironmentProviders {
  return provideAppInitializer(() => {
    const registry = inject(MatIconRegistry);
    const sanitizer = inject(DomSanitizer);
    for (const [name, path] of Object.entries(APP_ICONS)) {
      // Safe: static path data from @mdi/js, never user input.
      registry.addSvgIconLiteral(name, sanitizer.bypassSecurityTrustHtml(svg(path)));
    }
  });
}
